### ISSUE TITLE
Load time with large tilesets

### ISSUE THREAD

**Issue by ffomega** [solarus-games/solarus#986] opened 2016-09-16 23:51 UTC
Maps take between 8-10 seconds or longer to load (per map) using a large tileset.  This means that if you have several maps using the same large tileset, every map will take a minimum of 10 seconds to load.

This issue has been tested on a machine running Windows XP 32-bit, but has not been tested on other operating systems.

**Comment by christopho** [comment] 2017-01-25 13:48
Closing as duplicate of #1019

**Closed by christopho** 2017-01-25 13:48 UTC
