### ISSUE TITLE
Line artifacts when displaying animated tiles (SDL bug?)

### ISSUE THREAD

**Issue by AfroditaPeloAfro** [solarus-games/solarus#641] opened 2015-01-24 16:09 UTC
Hi,

I have been working with Solarus 1.3 for a while, both in Windows and Linux distributions, and I've seen there's a small bug when displaying animated tiles. Sometimes, depending on the position of the hero in the screen, there appears a small black line right at the edge of the tile. I attach an image to illustrate this:
![2015-01-24-165259_1280x1024_scrot](https://cloud.githubusercontent.com/assets/10685896/5887930/6e321616-a3ea-11e4-80f8-737dfd53ab04.png)
I've seen this happen in Mistery of Solarus DX and XD too, so it's a problem in the engine.

I suppose you're already aware of this, but I report it just in case. :) Thanks a lot for your work. Solarus is helping me a great deal, love it. (also, never posted in Github before, hope I'm doing it right)

**Comment by vlag** [comment] 2015-01-26 10:09
Hi, and welcome :)

Actually it's an SDL bug. As you probably noticed it, the bug doesn't occurs with the normal display, and with integer ratio (so 640x480 works fine, as well as 1280x960).
However there are no difference on the way to handle the normal and the resized display on the Solarus side, tiles are placed on the exact same pixel and have the exact same size.

The issue is already reported on the SDL bug tracker, and I hope it will be fixed for the next release :)

**Comment by AfroditaPeloAfro** [comment] 2015-01-26 12:04
Oh, I see. That makes sense. Thanks for clearing it up, and for the quick response! Let's hope it gets fixed :) For the moment, I'll simply change the background tileset color to something more neutral so the bug isn't so noticeable.

**Comment by christopho** [comment] 2015-01-26 13:41
Yes, it is an SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=2269
I think it only happens in fullscreen. It is a rounding issue with the black bars that are added by SDL when your ratio is larger than the one of the quest.
However I thought we had a workaround for this problem and I am surprised to see that you observe it in release 1.3. What is the resolution of your screen, and what is the size of the quest (defined in quest.dat)?

**Comment by christopho** [comment] 2015-01-26 13:44
If we can reproduce the bug in Solarus 1.3, maybe we should try the workaround suggested in the SDL bugzilla.

**Comment by AfroditaPeloAfro** [comment] 2015-01-26 15:48
Mmm. Well, I'm using a Gameboy screen size in my quest, 160x144, which is admitedly a weird screen size, but I get the same problem with the default 320x240. The glich only seems to happen when the screen size is increased by the user. The default x2 ratio works okay; it's when you make the screen bigger that there's a problem, no matter if the game is in fullscreen mode or not.

Mmm. Let me try different resolutions. I don't see the glich with a low resolution (the lowest I've been able to test is 800x600), but that may be simply because there's not much room to make the screen bigger. I do get the glich in 1024x768 and 1280x960 resolutions. With a 1280x1024 resolution, the glich is invisible in a maximised 320x240 screen, but when I test it with my own 160x144 screen size and make the screen as big as I can, I do see it. The line is faint, but there.

Now that you mention it, I do experience another graphical problem with animated tiles that I haven't been able to take a screenshot of. When the hero walks diagonally, the animated tiles get cut diagonally with a "stripe", as well, which follows the hero's direction. Something like this:
![captura](https://cloud.githubusercontent.com/assets/10685896/5902349/16391464-a57a-11e4-9687-5a364b92ca96.png)
I'm not entirely sure what this "stripe" is. But I just mention it in case it's related in some way to the other bug. (this one, however, happens no matter the resolution and no matter if the screen has been made bigger by the user or not) So far, animated tiles are the only kind of entities that seem to be causing me some trouble.

I've only been reading the quests documentation, not the engine documentation, so I am not yet completely aware of how the engine works internally. Hope this helps, though. If you want more information, just ask. :)

**Comment by vlag** [comment] 2015-02-15 09:18
@christopho : No, the bug I'm talking about is this one : 
https://bugzilla.libsdl.org/show_bug.cgi?id=2382

@AfroditaPeloAfro : I never experienced the animated tiles bug, but it is indeed something to dig.

The glitch indeed only appears when the window is resized by the user, into a non-multiple of the original size. Higher is the screen compared to its original size, wider will be the glitch, because either the start position of tiles will be rounded on the final window display, or because their end position will be truncated.
About the fullscreen issue, I guess that it is related to the screen resolution, but the cause seems to be the same.

**Comment by vlag** [comment] 2016-08-10 16:29
In case, I don't experience the line artifact anymore once SDL updated in 2.0.4.

**Comment by christopho** [comment] 2016-08-10 16:52
Good news! I will check for 1.5.1.

**Comment by christopho** [comment] 2016-10-01 14:05
Fix confirmed. No problem with SDL 2.0.4.

**Comment by christopho** [comment] 2016-10-01 14:06
Keeping the bug open to update the SDL version in the windows port.

**Comment by christopho** [comment] 2016-11-29 21:45
Done

**Closed by christopho** 2016-11-29 21:45 UTC
