### ISSUE TITLE
Fatal: Non-empty stack before LuaContext::update()

### ISSUE THREAD

**Issue by potamouch** [solarus-games/solarus#1104] opened 2017-10-27 04:56 UTC
I added on_obtaing eventa item and I had this error message. What is it ? 

Fatal: Non-empty stack before LuaContext::update()

**Comment by christopho** [comment] 2017-10-27 06:13
Please give the code to reproduce the issue

**Comment by christopho** [comment] 2017-10-27 12:45
I am assuming it was a duplicate of #1089 unless you still reproduce it.

**Closed as completed by christopho** 2017-10-27 12:45 UTC
Labels: bug
