### ISSUE TITLE
Crash when teleporting to a nonexistent layer

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#1119] opened 2017-12-03 05:15 UTC
Crash when teleporting to a nonexistent layer.

The bug was found by @christopho, using scrolling teleporters, somewhere in the streaming:
https://www.youtube.com/watch?v=a0pQjSfLT9Y

**Comment by christopho** [comment] 2017-12-03 16:29
Duplicate of #1015

**Closed as completed by christopho** 2017-12-03 16:29 UTC
Labels: bug
