### ISSUE TITLE
White Alpha Transparency

### ISSUE THREAD

**Issue by ffomega** [solarus-games/solarus#935] opened 2016-07-18 02:03 UTC
In the map editor, semi-transparent tiles look as intended regardless of what layer they are on.  During runtime, the alpha transparency looks correct as long as it appears on the same layer as the hero.  If the semi-transparent tile is on any layer higher than the hero, it darkens.  This occurs regardless of 2D acceleration.

**Comment by christopho** [comment] 2016-07-18 02:19
See the picture of http://forum.solarus-games.org/index.php/topic,694.msg3582.html#msg3582

**Comment by Diarandor** [comment] 2016-07-18 21:17
I am not sure, but these links may help:
http://stackoverflow.com/questions/23465933/sdl-how-to-blit-a-surface-onto-one-created-with-sdl-creatergbsurface-correctly
http://forums.libsdl.org/viewtopic.php?t=9542&sid=cc1329c9a41455bc02c6da5ba6bca34c

**Comment by christopho** [comment] 2016-07-18 22:51
First analysis shows that the problem is related to tiles pre-rendering. Tiles are drawn on an intermediate surface for performance, and then drawing this surface on the camera does not gives the same result as drawing on the camera directly. I am still investigating how to fix it.

**Comment by christopho** [comment] 2016-07-18 23:04
A solution could be to exclude semi-transparent tiles from the rendering optimization, like we already do for animated tiles.

**Comment by Diarandor** [comment] 2016-07-19 10:39
As you may know, the problem is probably due to the fact that the "alpha blend" formula of SDL is not associative:
```(A*B)*C ≠ A*(B*C),```
i.e., if you blend a surface A into a surface B and then the result into a surface C, what you get is different than if you render first blend B into C and then A into what you got before. Hence, using intermediate surfaces will alter the result, even if these are completely transparent. The "alpha blend" of SDL is only associative in the alpha component, but not in the RGB components, and I think there is no solution for this if we use the "alpha blend" of SDL.

(That does not happen with the alpha blending given in the wikipedia, which is associative and hence much better in my opinion, because that allows using intermediate surfaces without altering the result.)

I am afraid that probably the only way to fix this completely will be, as you say, not using the intermediate surfaces, so we would lose your optimization... :(

**Comment by Diarandor** [comment] 2016-07-19 10:58
Is there some better (and free) alternative to SDL2 library for the blending modes?

**Comment by christopho** [comment] 2016-07-19 11:34
Using blend mode "none" on the intermediate surface does not work because tiles are allowed to overlap. We must blend them all.

Excluding them from the pre-rendering optimization will be okay, as most tiles don't have transparency. Actually, the whole pre-rendering optimization itself is less crucial than in previous versions because drawing tiles is faster with 1.5 thanks to quadtrees.

**Comment by stdgregwar** [comment] 2018-04-29 22:27
I figured out how to address this problem.

We must have the intermediate surfaces to have alpha premultiplied.

I'll try to fix this for 1.6.

**Comment by christopho** [comment] 2018-06-04 17:55
Fixed in 1.6

**Closed by christopho** 2018-06-04 17:55 UTC
Labels: bug
